name: galaxy_web3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  blur: ^4.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_custom_clippers: ^2.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  gradient_borders: ^1.0.1
  intl: ^0.19.0
  morphable_shape: ^1.6.6
  neon_widgets: ^2.0.0
  sizer: ^3.0.4

dev_dependencies:
  build_runner: ^2.4.11
  copy_with_extension_gen: ^5.0.4
  flutter_gen_runner: null

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: null

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
